/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DecksController_listMine"];
        put?: never;
        post: operations["DecksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decks/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DecksController_duplicate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DecksController_getById"];
        put?: never;
        post?: never;
        delete: operations["DecksController_remove"];
        options?: never;
        head?: never;
        patch: operations["DecksController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeckSummaryDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Nombre de usuario del dueño
             * @example planeswalker
             */
            ownerUsername: string;
            name: string;
            /** @enum {string} */
            format: "commander" | "standard" | "pioneer" | "modern" | "legacy" | "vintage" | "pauper" | "brawl";
            /** @enum {string} */
            visibility: "public" | "unlisted" | "private";
            /** @description Suma de las cantidades de todas las zonas */
            cardCount: number;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateDeckDto: {
            /** @example Atraxa, superamigos */
            name: string;
            description?: string;
            /**
             * @default commander
             * @enum {string}
             */
            format: "commander" | "standard" | "pioneer" | "modern" | "legacy" | "vintage" | "pauper" | "brawl";
            /**
             * @default private
             * @enum {string}
             */
            visibility: "public" | "unlisted" | "private";
        };
        DeckEntryDto: {
            /** @description Id de Scryfall de la impresión */
            cardId: string;
            /** @enum {string} */
            board: "commander" | "main" | "sideboard" | "maybeboard";
            quantity: number;
            tags: string[];
        };
        DeckDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Nombre de usuario del dueño
             * @example planeswalker
             */
            ownerUsername: string;
            name: string;
            /** @enum {string} */
            format: "commander" | "standard" | "pioneer" | "modern" | "legacy" | "vintage" | "pauper" | "brawl";
            /** @enum {string} */
            visibility: "public" | "unlisted" | "private";
            /** @description Suma de las cantidades de todas las zonas */
            cardCount: number;
            /** Format: date-time */
            updatedAt: string;
            description: string | null;
            /** Format: date-time */
            createdAt: string;
            entries: components["schemas"]["DeckEntryDto"][];
        };
        UpdateDeckDto: {
            /** @example Atraxa, superamigos */
            name?: string;
            description?: string;
            /**
             * @default commander
             * @enum {string}
             */
            format: "commander" | "standard" | "pioneer" | "modern" | "legacy" | "vintage" | "pauper" | "brawl";
            /**
             * @default private
             * @enum {string}
             */
            visibility: "public" | "unlisted" | "private";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    DecksController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mazos del usuario, los más recientes primero */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckSummaryDto"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeckDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_duplicate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La copia, que empieza siempre privada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDto"];
                };
            };
            /** @description No existe o no lo puedes ver */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDto"];
                };
            };
            /** @description No existe o es privado de otro usuario */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe o no es tuyo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeckDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDto"];
                };
            };
            /** @description No existe o no es tuyo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
