/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FoldersController_listMine"];
        put?: never;
        post: operations["FoldersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/folders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["FoldersController_remove"];
        options?: never;
        head?: never;
        patch: operations["FoldersController_rename"];
        trace?: never;
    };
    "/v1/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DecksController_listMine"];
        put?: never;
        post: operations["DecksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decks/{id}/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DecksController_duplicate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DecksController_getById"];
        put?: never;
        post?: never;
        delete: operations["DecksController_remove"];
        options?: never;
        head?: never;
        patch: operations["DecksController_update"];
        trace?: never;
    };
    "/v1/decks/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DecksController_listVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decks/{id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["DecksController_updateEntries"];
        trace?: never;
    };
    "/v1/cards/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CardsController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cards/staples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CardsController_staples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthProvidersDto: {
            /** @description Proveedores OAuth con credenciales configuradas, en el orden en que se ofrecen */
            social: ("google" | "discord")[];
        };
        FolderDto: {
            /** Format: uuid */
            id: string;
            /** @example cEDH */
            name: string;
            /** @description Mazos que contiene */
            deckCount: number;
        };
        SaveFolderDto: {
            /** @example cEDH */
            name: string;
        };
        DeckSummaryDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Nombre de usuario del dueño
             * @example planeswalker
             */
            ownerUsername: string;
            name: string;
            /** @enum {string} */
            format: "commander" | "standard" | "pioneer" | "modern" | "legacy" | "vintage" | "pauper" | "brawl";
            /** @enum {string} */
            visibility: "public" | "unlisted" | "private";
            /** Format: uuid */
            folderId: string | null;
            tags: string[];
            /** @description Suma de las cantidades de todas las zonas */
            cardCount: number;
            /** @description Identidad de color en orden WUBRG: la del comandante, o la de todo el mazo */
            colorIdentity: ("W" | "U" | "B" | "R" | "G")[];
            /** @description Ilustración de portada: la del comandante, o la carta de más coste */
            coverImageUrl: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        DeckEntryInputDto: {
            /**
             * Format: uuid
             * @description Id de Scryfall de la impresión
             */
            cardId: string;
            /** @enum {string} */
            board: "commander" | "main" | "sideboard" | "maybeboard";
            quantity: number;
        };
        CreateDeckDto: {
            /** @example Atraxa, superamigos */
            name: string;
            description?: string;
            /**
             * @default commander
             * @enum {string}
             */
            format: "commander" | "standard" | "pioneer" | "modern" | "legacy" | "vintage" | "pauper" | "brawl";
            /**
             * @default private
             * @enum {string}
             */
            visibility: "public" | "unlisted" | "private";
            /**
             * Format: uuid
             * @description Carpeta de la biblioteca; `null` lo saca de la que tenga
             */
            folderId?: string | null;
            /** @description Se guardan en minúsculas y sin repetir */
            tags?: string[];
            /** @description Cartas iniciales. Las líneas repetidas (misma carta y zona) se suman. */
            entries?: components["schemas"]["DeckEntryInputDto"][];
        };
        CardDto: {
            /** @description Id de Scryfall de la impresión */
            id: string;
            oracleId: string | null;
            name: string;
            layout: string;
            /** @example {2}{R}{R} */
            manaCost: string | null;
            /** @description Valor de maná (antes CMC) */
            manaValue: number;
            /** @example Legendary Creature — Goblin Warrior */
            typeLine: string;
            oracleText: string | null;
            colors: ("W" | "U" | "B" | "R" | "G")[];
            colorIdentity: ("W" | "U" | "B" | "R" | "G")[];
            rarity: string;
            setCode: string;
            setName: string;
            collectorNumber: string;
            imageSmall: string | null;
            imageNormal: string | null;
            imageArtCrop: string | null;
            /** @description Precio en euros (Cardmarket) */
            priceEur: number | null;
            /** @description Precio en dólares (TCGplayer) */
            priceUsd: number | null;
            /**
             * @example {
             *       "commander": "legal",
             *       "modern": "not_legal"
             *     }
             */
            legalities: {
                [key: string]: string;
            };
            /** @description En la lista de "Game Changers" de Commander */
            gameChanger: boolean;
        };
        DeckEntryDto: {
            /** @description Id de Scryfall de la impresión */
            cardId: string;
            /** @enum {string} */
            board: "commander" | "main" | "sideboard" | "maybeboard";
            quantity: number;
            tags: string[];
            /** @description Datos de la carta; null si el catálogo local aún no la conoce */
            card: components["schemas"]["CardDto"] | null;
        };
        DeckDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Nombre de usuario del dueño
             * @example planeswalker
             */
            ownerUsername: string;
            name: string;
            /** @enum {string} */
            format: "commander" | "standard" | "pioneer" | "modern" | "legacy" | "vintage" | "pauper" | "brawl";
            /** @enum {string} */
            visibility: "public" | "unlisted" | "private";
            /** Format: uuid */
            folderId: string | null;
            tags: string[];
            /** @description Suma de las cantidades de todas las zonas */
            cardCount: number;
            /** @description Identidad de color en orden WUBRG: la del comandante, o la de todo el mazo */
            colorIdentity: ("W" | "U" | "B" | "R" | "G")[];
            /** @description Ilustración de portada: la del comandante, o la carta de más coste */
            coverImageUrl: string | null;
            /** Format: date-time */
            updatedAt: string;
            description: string | null;
            /** Format: date-time */
            createdAt: string;
            entries: components["schemas"]["DeckEntryDto"][];
            /** @description Si quien lo pide puede editarlo (es su dueño) */
            viewerCanEdit: boolean;
        };
        DeckVersionChangeDto: {
            /** @description Id de Scryfall de la impresión */
            cardId: string;
            /** @enum {string} */
            board: "commander" | "main" | "sideboard" | "maybeboard";
            /** @description Copias que había antes; 0 si la carta no estaba */
            from: number;
            /** @description Copias que hay ahora; 0 si se quitó */
            to: number;
            /** @description Datos de la carta; null si el catálogo local ya no la conoce */
            card: components["schemas"]["CardDto"] | null;
        };
        DeckVersionDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @description Cuándo empezaron los cambios
             */
            createdAt: string;
            changes: components["schemas"]["DeckVersionChangeDto"][];
        };
        UpdateDeckDto: {
            /** @example Atraxa, superamigos */
            name?: string;
            description?: string;
            /**
             * @default commander
             * @enum {string}
             */
            format: "commander" | "standard" | "pioneer" | "modern" | "legacy" | "vintage" | "pauper" | "brawl";
            /**
             * @default private
             * @enum {string}
             */
            visibility: "public" | "unlisted" | "private";
            /**
             * Format: uuid
             * @description Carpeta de la biblioteca; `null` lo saca de la que tenga
             */
            folderId?: string | null;
            /** @description Se guardan en minúsculas y sin repetir */
            tags?: string[];
        };
        EntryChangeDto: {
            /**
             * Format: uuid
             * @description Id de Scryfall de la impresión
             */
            cardId: string;
            /** @enum {string} */
            board: "commander" | "main" | "sideboard" | "maybeboard";
            /** @description Cantidad final de esa carta en esa zona. 0 la quita. */
            quantity: number;
            /** @description Etiquetas de la carta en este mazo ("rampa", "robo"…): sustituyen a las que tuviera. Sin este campo se conservan. Se guardan en minúsculas y sin repetir. */
            tags?: string[];
        };
        UpdateEntriesDto: {
            changes: components["schemas"]["EntryChangeDto"][];
        };
        StapleGroupDto: {
            /** @enum {string} */
            role: "ramp" | "draw" | "removal" | "land";
            /** @description Las más jugadas primero */
            cards: components["schemas"]["CardDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    AuthController_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProvidersDto"];
                };
            };
        };
    };
    FoldersController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Carpetas del usuario, por nombre */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDto"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FoldersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveFolderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya tienes una carpeta con ese nombre */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FoldersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FoldersController_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveFolderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya tienes una carpeta con ese nombre */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_listMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mazos del usuario, los más recientes primero */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckSummaryDto"][];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeckDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_duplicate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La copia, que empieza siempre privada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDto"];
                };
            };
            /** @description No existe o no lo puedes ver */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDto"];
                };
            };
            /** @description No existe o es privado de otro usuario */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe o no es tuyo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeckDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDto"];
                };
            };
            /** @description No existe o no es tuyo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_listVersions: {
        parameters: {
            query?: {
                /** @description Versiones que se devuelven, de la más reciente hacia atrás */
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versiones, la más reciente primero */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckVersionDto"][];
                };
            };
            /** @description No existe o no es tuyo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DecksController_updateEntries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEntriesDto"];
            };
        };
        responses: {
            /** @description El mazo con los cambios aplicados */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckDto"];
                };
            };
            /** @description Carta que no existe o demasiadas cartas distintas */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No existe o no es tuyo */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CardsController_search: {
        parameters: {
            query: {
                q: string;
                /** @description Solo cartas que quepan en esta identidad de color, p. ej. `RG`. `C` = solo incoloras. */
                identity?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Una impresión por carta, las más jugadas primero */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDto"][];
                };
            };
        };
    };
    CardsController_staples: {
        parameters: {
            query?: {
                /** @description Identidad de color del comandante, p. ej. `RG`. `C` = solo incoloras. Sin ella, no se filtra. */
                identity?: string;
                /** @description Cartas por función. Se piden de más para poder descartar las que ya están. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Un grupo por función, en el orden en que se monta un mazo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StapleGroupDto"][];
                };
            };
        };
    };
}
